version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - dice-networks
    environment:
      - TZ=Asia/Seoul

  redis-cache:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - dice-networks
    environment:
      - TZ=Asia/Seoul

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15050:15672

  db:
    image: mysql:latest
    ports:
      - '3307:3306'
    networks:
      - dice-networks
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1595@!
      MYSQL_DATABASE: core
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1595@!

networks:
  dice-networks:
