version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15050:15672
  # mysql-db:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: qwer1595
  #     MYSQL_DATABASE: nest-test
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: qwer1595
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - my-network

volumes:
  mysql-data:
