version: '3'
services:
  auth:
    build:
      context: ./apps/auth-server
    ports:
      - 8280:8280
    networks:
      - dice-networks
    depends_on:
      - redis
      - db
      - redis-cache
      - rabbitmq

  core:
    build:
      context: ./apps/core-server
    ports:
      - 8080:8080
    networks:
      - dice-networks
    depends_on:
      - redis
      - db
      - redis-cache
      - rabbitmq

  log:
    build:
      context: ./apps/log-server
    ports:
      - 8180:8180
    networks:
      - dice-networks
    depends_on:
      - redis
      - db
      - redis-cache
      - rabbitmq

  push:
    build:
      context: ./apps/push-server
    ports:
      - 8380:8380
    networks:
      - dice-networks
    depends_on:
      - redis
      - db
      - redis-cache
      - rabbitmq

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - dice-networks
    environment:
      - TZ=Asia/Seoul

  redis-cache:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - dice-networks
    environment:
      - TZ=Asia/Seoul

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15050:15672

  db:
    image: mysql:latest
    ports:
      - '3307:3306'
    networks:
      - dice-networks
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1595@!
      MYSQL_DATABASE: core
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1595@!
    command: --default-time-zone=Asia/Seoul

  db-master:
    image: mysql:8.0
    restart: always
    networks:
      - dice-networks
    ports:
      - '3308:3306'
    volumes:
      - ./db-master:/var/lib/mysql
      - ./db-master:/var/lib/mysql-files
      - ./config/master.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1595@!
      MYSQL_ROOT_PASSWORD: qwer1595@!
    command: --default-time-zone=Asia/Seoul

  db-slave:
    image: mysql:8.0
    restart: always
    ports:
      - '3309:3306'
    volumes:
      - ./db-slave:/var/lib/mysql
      - ./db-slave:/var/lib/mysql-files
      - ./config/slave.cnf:/etc/mysql/my.cnf
    networks:
      - dice-networks
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1595@!
      MYSQL_ROOT_PASSWORD: qwer1595@!
    command: --default-time-zone=Asia/Seoul

networks:
  dice-networks:
